rime.lua

1  config  只讀取一次
2 input(translation)  不要全部倒出至 table ,浪費mem and 時間

改善 reduce_english_filter() 效率

---

default.yaml
double_pinyin_mspy.schema.yaml

feat: 添加微软双拼配置

---

double_pinyin.schema.yaml
double_pinyin_flypy.schema.yaml
double_pinyin_mspy.schema.yaml
double_pinyin_ziguang.schema.yaml
melt_eng.schema.yaml
rime.lua
rime_ice.schema.yaml

这是用户词吗？.lua

---

others/script/rime/cn_en.go

feat: 生成适用于智能ABC双拼的混拼字典

---

lua/date_translator.lua
lua/unicode.lua

fix getting current time multiple times error

refactor: refactor date translator

---

README.md

README.md 修复超链接

---

en_dicts/en_ext.dict.yaml

Update en_ext.dict.yaml add OpenWrt

---

weasel_style.yaml

- 将文档中的值改为 weasel.yaml 的默认值，字体部分给出参考示例和链接
- 更新了小狼毫新的一些设定

doc: update weasel_style.yaml (db79168)

---

lua/en_spacer.lua
rime.lua

#492 
@fastfading 站在 Chat-GPT 的肩膀上🐶

lua: 英文词条上屏自动添加空格

---

rime_ice.schema.yaml
weasel.yaml

- 删掉了一些原先没有的 app_options，让用户自己设定
- 修改、添加了一些文档
- weasel 字体上添加了 emoji 用到的 keycap 字符

docs: update weasel.yaml

---

lua/select_character.lua

- 将获取按键移动到 init 函数
- 简化了中文取字方法
- 预先判断无候选（加入了 alphabet 但无候选词）防止 error log 产生，使用 input

refactor: lua select_char

---

lua/pin_cand_filter.lua

fix: init function failed if pin_cand_filter: is empty
feat: handle cands converted by simplifier filter.
close #586

fix pin lua

---

en_dicts/en_ext.dict.yaml

dict: 日常更新

---

README.md

大多数项目都要求引用时附带协议（或其链接），一些项目还要求署名。本 PR 补充。

docs: add license info

---

double_pinyin.schema.yaml
double_pinyin_abc.schema.yaml
double_pinyin_flypy.schema.yaml
double_pinyin_mspy.schema.yaml
double_pinyin_sogou.schema.yaml
double_pinyin_ziguang.schema.yaml
lua/auto_commit_single_punct.lua
rime_ice.schema.yaml

fix: committed incorrect puncts when user sets non-corresponding keys.
fix: lua hijacked keys when in ascii_mode
fix: handle keys correctly combined with shift
close #673

lua: fix #673

---

others/script/rime/cn_en.go

对于含飞键双拼方案，单个拼音（全拼）可能映射至多个双拼（键位组合），因此需自动匹配生成多条。

feat:支持含飞键双拼方案更新中英混输词库

---

lua/is_in_user_dict.lua

支持 table_translator 造出的用户词。
使用哈希表减少了不必要的比较。

fix: is_in_user_dict

---

en_dicts/en.dict.yaml

add word immersive, generative to English dict

add 2 words to English dict

---

en_dicts/en_ext.dict.yaml

dict: Add entries for V8 engine to en_ext.dict

---

en_dicts/en_ext.dict.yaml

Terraform: https://www.terraform.io/

Add Terraform to en_dicts/en_ext.dict.yaml

---

double_pinyin.schema.yaml
double_pinyin_abc.schema.yaml
double_pinyin_flypy.schema.yaml
double_pinyin_mspy.schema.yaml
double_pinyin_sogou.schema.yaml
double_pinyin_ziguang.schema.yaml

fix: buang -> biang

---

cn_dicts/8105.dict.yaml

调整词频：都市>电商
调整词频：修改>新股
调整词频：绵羊>绵阳

"𤭢了"从单字表移动到base词库 && 调整词频

---

en_dicts/en_ext.dict.yaml

dict: Add Dockerfile and Docker Hub to en_ext.dict.yaml

---

en_dicts/en.dict.yaml
en_dicts/en_ext.dict.yaml

https://en.wikipedia.org/wiki/GameCube

Fix the cap: GameCube

---

en_dicts/en.dict.yaml

Add word 'epilogue' to en dict

---

en_dicts/en_ext.dict.yaml

参见：
- #1109
添加的词语和计算机应该是强相关的，且应该都比较常用，并且基本没有重码。

dict(en): 增添常用计算机相关术语及缩写

---

cn_dicts/41448.dict.yaml
radical_pinyin.dict.yaml

dict: add hanzi

---

en_dicts/en.dict.yaml
en_dicts/en_ext.dict.yaml

1. 补充炼金术师alchemist（有alchemy而缺了alchemist），天王星Uranus（太阳系行星似乎就缺了Uranus），增加棒棒糖lollipop，蒲公英dandelion
2. 增加机器学习常用的tensor，TensorFlow和PyTorch
3. 取消注释mu以便于输入希腊字母μ

dict(en): Expand vocabulary

---

go.work

通过 Go Workspace 配置解决 VSCode 中 Go 插件和 Code Runner 的模块路径报错问题。
修改内容:
- 新增 go.work 文件显式声明 others/script 模块路径
- 不涉及其他代码变更，仅工具链配置

chore: Set up Go Workspace to streamline VSCode tooling

---

rime_ice.schema.yaml

chore: 后移bus在候选项中的位置
